###
GET http://localhost:8000/

###
GET http://localhost:8000/api/crypto?crypto=ethereum

###
POST http://localhost:8000/api/postData
Content-Type: application/json

{
    "inputData": "Crypto of the day"
}

###
GET https://crypto-data-expressjs.onrender.com/api/crypto?crypto=ethereum